# Generated by Django 4.1.6 on 2023-02-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="uploaded", new_name="updated",
        ),
    ]
